# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f8756e2aa7197dc85f805e342af294a1b0a0de5cbd5ed3f137e51b60497eae893169cdfc05dd244f460d8f2d0ad0a1fb2256491e2f27be5c0a1527f6cb3b61

test:
  secret_key_base: 462b68bc1b79dcde914361d338e2e555563039f2bc1b2aad48ed9b3ff657cf639f597b94315df80fb875200d0751c8973fee82211371cf1f2dbf2ff27eeef707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
